### ISSUE TITLE
4 new blog posts

### ISSUE THREAD

**Issue by mbseid** [naytev/naytev-blog#3]
- [ ] Find image you need
- [ ] lame stock images
- [ ] three best images types -- not ready
- [ ] clickbait article -- doesn't have title

**Comment by mbseid** [comment]
@caramtucker can you fill in the questions you aren't sure about so I can double check when I post them.

**Comment by caramtucker** [comment]
Lame stock images: please make sure that an italicized caption appears below all three bunnies and beneath the "new focus" image. 

Lame stock images: please make sure that the 'bad' and 'good' image trios display together on one line, horizontally.

3 Best Image Types: Please make sure that the illustration from Debbie Scheller has a caption containing credits.

Find image you need: please make sure the "ladybug grid" image has a caption containing credits.
